# Generated by Django 2.2.3 on 2019-10-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191010_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.IntegerField(blank=True, choices=[(1, 'İlkokul'), (2, 'Ortaokul'), (3, 'Lise'), (4, 'Ön Lisans'), (5, 'Lisans'), (6, 'Yüksek Lisans'), (7, 'Doktora')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Erkek'), (2, 'Kadın'), (3, 'Diğer'), (4, 'Belirtmek istemiyorum')], null=True),
        ),
    ]
