# Generated by Django 2.2.3 on 2019-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191010_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[('İlkokul', 'İlkokul'), ('Ortaokul', 'Ortaokul'), ('Lise', 'Lise'), ('Ön Lisans', 'Ön Lisans'), ('Lisans', 'Lisans'), ('Yüksek Lisans', 'Yüksek Lisans'), ('Doktora', 'Doktora')], default='Lise', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Diğer', 'Diğer'), ('Belirtmek istemiyorum', 'Belirtmek istemiyorum')], default='Erkek', max_length=20),
        ),
    ]
