# Generated by Django 2.2.3 on 2019-10-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191011_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='owner_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='User ID'),
            preserve_default=False,
        ),
    ]
